export const COUNTRIES = [
  { value: 'afghanistan', label: 'Afghanistan', flag: '🇦🇫' },
  { value: 'albania', label: 'Albania', flag: '🇦🇱' },
  { value: 'algeria', label: 'Algeria', flag: '🇩🇿' },
  { value: 'argentina', label: 'Argentina', flag: '🇦🇷' },
  { value: 'armenia', label: 'Armenia', flag: '🇦🇲' },
  { value: 'australia', label: 'Australia', flag: '🇦🇺' },
  { value: 'austria', label: 'Austria', flag: '🇦🇹' },
  { value: 'azerbaijan', label: 'Azerbaijan', flag: '🇦🇿' },
  { value: 'bahrain', label: 'Bahrain', flag: '🇧🇭' },
  { value: 'bangladesh', label: 'Bangladesh', flag: '🇧🇩' },
  { value: 'belarus', label: 'Belarus', flag: '🇧🇾' },
  { value: 'belgium', label: 'Belgium', flag: '🇧🇪' },
  { value: 'bolivia', label: 'Bolivia', flag: '🇧🇴' },
  { value: 'bosnia-and-herzegovina', label: 'Bosnia and Herzegovina', flag: '🇧🇦' },
  { value: 'botswana', label: 'Botswana', flag: '🇧🇼' },
  { value: 'brazil', label: 'Brazil', flag: '🇧🇷' },
  { value: 'bulgaria', label: 'Bulgaria', flag: '🇧🇬' },
  { value: 'burkina-faso', label: 'Burkina Faso', flag: '🇧🇫' },
  { value: 'cambodia', label: 'Cambodia', flag: '🇰🇭' },
  { value: 'cameroon', label: 'Cameroon', flag: '🇨🇲' },
  { value: 'canada', label: 'Canada', flag: '🇨🇦' },
  { value: 'central-african-republic', label: 'Central African Republic', flag: '🇨🇫' },
  { value: 'chad', label: 'Chad', flag: '🇹🇩' },
  { value: 'chile', label: 'Chile', flag: '🇨🇱' },
  { value: 'china', label: 'China', flag: '🇨🇳' },
  { value: 'colombia', label: 'Colombia', flag: '🇨🇴' },
  { value: 'costa-rica', label: 'Costa Rica', flag: '🇨🇷' },
  { value: 'cote-divoire', label: 'Côte d\'Ivoire', flag: '🇨🇮' },
  { value: 'croatia', label: 'Croatia', flag: '🇭🇷' },
  { value: 'cuba', label: 'Cuba', flag: '🇨🇺' },
  { value: 'cyprus', label: 'Cyprus', flag: '🇨🇾' },
  { value: 'czech-republic', label: 'Czech Republic', flag: '🇨🇿' },
  { value: 'denmark', label: 'Denmark', flag: '🇩🇰' },
  { value: 'dominican-republic', label: 'Dominican Republic', flag: '🇩🇴' },
  { value: 'ecuador', label: 'Ecuador', flag: '🇪🇨' },
  { value: 'egypt', label: 'Egypt', flag: '🇪🇬' },
  { value: 'estonia', label: 'Estonia', flag: '🇪🇪' },
  { value: 'eswatini', label: 'Eswatini', flag: '🇸🇿' },
  { value: 'ethiopia', label: 'Ethiopia', flag: '🇪🇹' },
  { value: 'fiji', label: 'Fiji', flag: '🇫🇯' },
  { value: 'finland', label: 'Finland', flag: '🇫🇮' },
  { value: 'france', label: 'France', flag: '🇫🇷' },
  { value: 'georgia', label: 'Georgia', flag: '🇬🇪' },
  { value: 'germany', label: 'Germany', flag: '🇩🇪' },
  { value: 'ghana', label: 'Ghana', flag: '🇬🇭' },
  { value: 'greece', label: 'Greece', flag: '🇬🇷' },
  { value: 'guatemala', label: 'Guatemala', flag: '🇬🇹' },
  { value: 'honduras', label: 'Honduras', flag: '🇭🇳' },
  { value: 'hungary', label: 'Hungary', flag: '🇭🇺' },
  { value: 'iceland', label: 'Iceland', flag: '🇮🇸' },
  { value: 'india', label: 'India', flag: '🇮🇳' },
  { value: 'indonesia', label: 'Indonesia', flag: '🇮🇩' },
  { value: 'iran', label: 'Iran', flag: '🇮🇷' },
  { value: 'iraq', label: 'Iraq', flag: '🇮🇶' },
  { value: 'ireland', label: 'Ireland', flag: '🇮🇪' },
  { value: 'israel', label: 'Israel', flag: '🇮🇱' },
  { value: 'italy', label: 'Italy', flag: '🇮🇹' },
  { value: 'jamaica', label: 'Jamaica', flag: '🇯🇲' },
  { value: 'japan', label: 'Japan', flag: '🇯🇵' },
  { value: 'jordan', label: 'Jordan', flag: '🇯🇴' },
  { value: 'kazakhstan', label: 'Kazakhstan', flag: '🇰🇿' },
  { value: 'kenya', label: 'Kenya', flag: '🇰🇪' },
  { value: 'kosovo', label: 'Kosovo', flag: '🇽🇰' },
  { value: 'kuwait', label: 'Kuwait', flag: '🇰🇼' },
  { value: 'kyrgyzstan', label: 'Kyrgyzstan', flag: '🇰🇬' },
  { value: 'laos', label: 'Laos', flag: '🇱🇦' },
  { value: 'latvia', label: 'Latvia', flag: '🇱🇻' },
  { value: 'lebanon', label: 'Lebanon', flag: '🇱🇧' },
  { value: 'lesotho', label: 'Lesotho', flag: '🇱🇸' },
  { value: 'libya', label: 'Libya', flag: '🇱🇾' },
  { value: 'lithuania', label: 'Lithuania', flag: '🇱🇹' },
  { value: 'luxembourg', label: 'Luxembourg', flag: '🇱🇺' },
  { value: 'madagascar', label: 'Madagascar', flag: '🇲🇬' },
  { value: 'malaysia', label: 'Malaysia', flag: '🇲🇾' },
  { value: 'mali', label: 'Mali', flag: '🇲🇱' },
  { value: 'mauritius', label: 'Mauritius', flag: '🇲🇺' },
  { value: 'mexico', label: 'Mexico', flag: '🇲🇽' },
  { value: 'moldova', label: 'Moldova', flag: '🇲🇩' },
  { value: 'mongolia', label: 'Mongolia', flag: '🇲🇳' },
  { value: 'montenegro', label: 'Montenegro', flag: '🇲🇪' },
  { value: 'morocco', label: 'Morocco', flag: '🇲🇦' },
  { value: 'myanmar', label: 'Myanmar', flag: '🇲🇲' },
  { value: 'namibia', label: 'Namibia', flag: '🇳🇦' },
  { value: 'nepal', label: 'Nepal', flag: '🇳🇵' },
  { value: 'netherlands', label: 'Netherlands', flag: '🇳🇱' },
  { value: 'new-caledonia', label: 'New Caledonia', flag: '🇳🇨' },
  { value: 'new-zealand', label: 'New Zealand', flag: '🇳🇿' },
  { value: 'nicaragua', label: 'Nicaragua', flag: '🇳🇮' },
  { value: 'niger', label: 'Niger', flag: '🇳🇪' },
  { value: 'nigeria', label: 'Nigeria', flag: '🇳🇬' },
  { value: 'north-korea', label: 'North Korea', flag: '🇰🇵' },
  { value: 'north-macedonia', label: 'North Macedonia', flag: '🇲🇰' },
  { value: 'norway', label: 'Norway', flag: '🇳🇴' },
  { value: 'oman', label: 'Oman', flag: '🇴🇲' },
  { value: 'pakistan', label: 'Pakistan', flag: '🇵🇰' },
  { value: 'panama', label: 'Panama', flag: '🇵🇦' },
  { value: 'papua-new-guinea', label: 'Papua New Guinea', flag: '🇵🇬' },
  { value: 'paraguay', label: 'Paraguay', flag: '🇵🇾' },
  { value: 'peru', label: 'Peru', flag: '🇵🇪' },
  { value: 'philippines', label: 'Philippines', flag: '🇵🇭' },
  { value: 'poland', label: 'Poland', flag: '🇵🇱' },
  { value: 'portugal', label: 'Portugal', flag: '🇵🇹' },
  { value: 'qatar', label: 'Qatar', flag: '🇶🇦' },
  { value: 'romania', label: 'Romania', flag: '🇷🇴' },
  { value: 'russia', label: 'Russia', flag: '🇷🇺' },
  { value: 'rwanda', label: 'Rwanda', flag: '🇷🇼' },
  { value: 'saudi-arabia', label: 'Saudi Arabia', flag: '🇸🇦' },
  { value: 'senegal', label: 'Senegal', flag: '🇸🇳' },
  { value: 'serbia', label: 'Serbia', flag: '🇷🇸' },
  { value: 'singapore', label: 'Singapore', flag: '🇸🇬' },
  { value: 'slovakia', label: 'Slovakia', flag: '🇸🇰' },
  { value: 'slovenia', label: 'Slovenia', flag: '🇸🇮' },
  { value: 'solomon-islands', label: 'Solomon Islands', flag: '🇸🇧' },
  { value: 'south-africa', label: 'South Africa', flag: '🇿🇦' },
  { value: 'south-korea', label: 'South Korea', flag: '🇰🇷' },
  { value: 'spain', label: 'Spain', flag: '🇪🇸' },
  { value: 'sri-lanka', label: 'Sri Lanka', flag: '🇱🇰' },
  { value: 'sudan', label: 'Sudan', flag: '🇸🇩' },
  { value: 'sweden', label: 'Sweden', flag: '🇸🇪' },
  { value: 'switzerland', label: 'Switzerland', flag: '🇨🇭' },
  { value: 'syria', label: 'Syria', flag: '🇸🇾' },
  { value: 'taiwan', label: 'Taiwan', flag: '🇹🇼' },
  { value: 'tajikistan', label: 'Tajikistan', flag: '🇹🇯' },
  { value: 'tanzania', label: 'Tanzania', flag: '🇹🇿' },
  { value: 'thailand', label: 'Thailand', flag: '🇹🇭' },
  { value: 'tunisia', label: 'Tunisia', flag: '🇹🇳' },
  { value: 'turkey', label: 'Turkey', flag: '🇹🇷' },
  { value: 'turkmenistan', label: 'Turkmenistan', flag: '🇹🇲' },
  { value: 'uganda', label: 'Uganda', flag: '🇺🇬' },
  { value: 'ukraine', label: 'Ukraine', flag: '🇺🇦' },
  { value: 'united-arab-emirates', label: 'United Arab Emirates', flag: '🇦🇪' },
  { value: 'united-kingdom', label: 'United Kingdom', flag: '🇬🇧' },
  { value: 'united-states', label: 'United States', flag: '🇺🇸' },
  { value: 'uruguay', label: 'Uruguay', flag: '🇺🇾' },
  { value: 'uzbekistan', label: 'Uzbekistan', flag: '🇺🇿' },
  { value: 'vanuatu', label: 'Vanuatu', flag: '🇻🇺' },
  { value: 'venezuela', label: 'Venezuela', flag: '🇻🇪' },
  { value: 'vietnam', label: 'Vietnam', flag: '🇻🇳' },
  { value: 'yemen', label: 'Yemen', flag: '🇾🇪' },
  { value: 'zimbabwe', label: 'Zimbabwe', flag: '🇿🇼' },
];

export const LANGUAGES = [
  { value: 'ar', label: 'Arabic', flag: '🇸🇦' },
  { value: 'bg', label: 'Bulgarian', flag: '🇧🇬' },
  { value: 'zh', label: 'Chinese', flag: '🇨🇳' },
  { value: 'hr', label: 'Croatian', flag: '🇭🇷' },
  { value: 'cs', label: 'Czech', flag: '🇨🇿' },
  { value: 'da', label: 'Danish', flag: '🇩🇰' },
  { value: 'nl', label: 'Dutch', flag: '🇳🇱' },
  { value: 'en', label: 'English', flag: '🇬🇧' },
  { value: 'et', label: 'Estonian', flag: '🇪🇪' },
  { value: 'tl', label: 'Filipino', flag: '🇵🇭' },
  { value: 'fi', label: 'Finnish', flag: '🇫🇮' },
  { value: 'fr', label: 'French', flag: '🇫🇷' },
  { value: 'de', label: 'German', flag: '🇩🇪' },
  { value: 'el', label: 'Greek', flag: '🇬🇷' },
  { value: 'he', label: 'Hebrew', flag: '🇮🇱' },
  { value: 'hi', label: 'Hindi', flag: '🇮🇳' },
  { value: 'hu', label: 'Hungarian', flag: '🇭🇺' },
  { value: 'id', label: 'Indonesian', flag: '🇮🇩' },
  { value: 'it', label: 'Italian', flag: '🇮🇹' },
  { value: 'ja', label: 'Japanese', flag: '🇯🇵' },
  { value: 'ko', label: 'Korean', flag: '🇰🇷' },
  { value: 'lv', label: 'Latvian', flag: '🇱🇻' },
  { value: 'lt', label: 'Lithuanian', flag: '🇱🇹' },
  { value: 'ms', label: 'Malay', flag: '🇲🇾' },
  { value: 'no', label: 'Norwegian', flag: '🇳🇴' },
  { value: 'pl', label: 'Polish', flag: '🇵🇱' },
  { value: 'pt', label: 'Portuguese', flag: '🇵🇹' },
  { value: 'ro', label: 'Romanian', flag: '🇷🇴' },
  { value: 'ru', label: 'Russian', flag: '🇷🇺' },
  { value: 'sr', label: 'Serbian', flag: '🇷🇸' },
  { value: 'sk', label: 'Slovak', flag: '🇸🇰' },
  { value: 'sl', label: 'Slovenian', flag: '🇸🇮' },
  { value: 'es', label: 'Spanish', flag: '🇪🇸' },
  { value: 'sv', label: 'Swedish', flag: '🇸🇪' },
  { value: 'th', label: 'Thai', flag: '🇹🇭' },
  { value: 'tr', label: 'Turkish', flag: '🇹🇷' },
  { value: 'uk', label: 'Ukrainian', flag: '🇺🇦' },
  { value: 'vi', label: 'Vietnamese', flag: '🇻🇳' },
];


export const MAIN_CATEGORIES = [
  'Animala / Pets',
  'Education',
  'Food',
  'Lifestyle',
  'Politics',
  'Art',
  'Energy & Solar Energy',
  'Gambling',
  'Marijuana / Vaporizers',
  'Real Estate',
  'Auto',
  'Entertainment & Music',
  'Gaming',
  'Marketing',
  'Beauty',
  'Environment',
  'General',
  'Medical',
  'Environment Safety',
  'Blogging',
  'Events',
  'Business / Entrepreneur',
  'Computer & Electronics',
  'Directory',
  'Family / Parenting',
  'Fashion',
  'Finance',
  'Health & Fitness',
  'Home & Garden',
  'Italian Sites',
  'Legal',
  'News',
  'Other',
  'Outdoors',
  'Photography',
  'SEO',
  'Sex & Adult',
  'Shopping',
];

export const NAVIGATION_ITEMS = [
  { label: 'Marketplace', href: '/marketplace', active: false },
  { label: 'My websites', href: '/', active: true },
  { label: 'My Orders', href: '/orders', active: false },
  { label: 'My projects', href: '/projects', active: false },
  { label: 'Recieved orders', href: '/received-orders', active: false },
];
