import { type ClassValue, clsx } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

function flagEmojiToCountryCode(flagEmoji: string): string | null {
  const FLAG_EMOJI_MAP: Record<string, string> = {
    "🇺🇸": "us",
    "🇬🇧": "gb",
    "🇪🇸": "es",
    "🇫🇷": "fr",
    "🇩🇪": "de",
    "🇮🇹": "it",
    "🇨🇦": "ca",
    "🇦🇺": "au",
    "🇧🇷": "br",
    "🇳🇱": "nl",
    "🇷🇺": "ru",
    "🇯🇵": "jp",
    "🇰🇷": "kr",
    "🇨🇳": "cn",
    "🇮🇳": "in",
    "🇲🇽": "mx",
    "🇦🇷": "ar",
    "🇨🇱": "cl",
    "🇨🇴": "co",
    "🇵🇪": "pe",
    "🇻🇪": "ve",
    "🇪🇨": "ec",
    "🇺🇾": "uy",
    "🇵🇾": "py",
    "🇧🇴": "bo",
    "🇬🇹": "gt",
    "🇨🇷": "cr",
    "🇵🇦": "pa",
    "🇳🇮": "ni",
    "🇭🇳": "hn",
    "🇯🇲": "jm",
    "🇩🇴": "do",
    "🇨🇺": "cu",
    "🇸🇪": "se",
    "🇳🇴": "no",
    "🇩🇰": "dk",
    "🇫🇮": "fi",
    "🇮🇸": "is",
    "🇵🇱": "pl",
    "🇨🇿": "cz",
    "🇸🇰": "sk",
    "🇭🇺": "hu",
    "🇦🇹": "at",
    "🇨🇭": "ch",
    "🇧🇪": "be",
    "🇱🇺": "lu",
    "🇮🇪": "ie",
    "🇵🇹": "pt",
    "🇬🇷": "gr",
    "🇹🇷": "tr",
    "🇷🇴": "ro",
    "🇧🇬": "bg",
    "🇺🇦": "ua",
    "🇧🇾": "by",
    "🇱🇹": "lt",
    "🇱🇻": "lv",
    "🇪🇪": "ee",
    "🇷🇸": "rs",
    "🇭🇷": "hr",
    "🇸🇮": "si",
    "🇧🇦": "ba",
    "🇲🇰": "mk",
    "🇦🇱": "al",
    "🇲🇪": "me",
    "🇽🇰": "xk",
    "🇲🇩": "md",
    "🇬🇪": "ge",
    "🇦🇲": "am",
    "🇦🇿": "az",
    "🇰🇿": "kz",
    "🇺🇿": "uz",
    "🇰🇬": "kg",
    "🇹🇯": "tj",
    "🇹🇲": "tm",
    "🇲🇳": "mn",
    "🇦🇫": "af",
    "🇵🇰": "pk",
    "🇧🇩": "bd",
    "🇱🇰": "lk",
    "🇳🇵": "np",
    "🇹🇭": "th",
    "🇻🇳": "vn",
    "🇰🇭": "kh",
    "🇱🇦": "la",
    "🇲🇲": "mm",
    "🇲🇾": "my",
    "🇸🇬": "sg",
    "🇮🇩": "id",
    "🇵🇭": "ph",
    "🇹🇼": "tw",
    "🇮🇷": "ir",
    "🇮🇶": "iq",
    "🇸🇾": "sy",
    "🇯🇴": "jo",
    "🇱🇧": "lb",
    "🇮🇱": "il",
    "🇸🇦": "sa",
    "🇦🇪": "ae",
    "🇶🇦": "qa",
    "🇰🇼": "kw",
    "🇧🇭": "bh",
    "🇴🇲": "om",
    "🇾🇪": "ye",
    "🇪🇬": "eg",
    "🇱🇾": "ly",
    "🇹🇳": "tn",
    "🇩🇿": "dz",
    "🇲🇦": "ma",
    "🇸🇩": "sd",
    "🇪🇹": "et",
    "🇰🇪": "ke",
    "🇹🇿": "tz",
    "🇺🇬": "ug",
    "🇷🇼": "rw",
    "🇿🇦": "za",
    "🇳🇬": "ng",
    "🇬🇭": "gh",
    "🇨🇮": "ci",
    "🇸🇳": "sn",
    "🇲🇱": "ml",
    "🇧🇫": "bf",
    "🇳🇪": "ne",
    "🇹🇩": "td",
    "🇨🇲": "cm",
    "🇨🇫": "cf",
    "🇿🇼": "zw",
    "🇧🇼": "bw",
    "🇳🇦": "na",
    "🇱🇸": "ls",
    "🇸🇿": "sz",
    "🇲🇬": "mg",
    "🇲🇺": "mu",
    "🇳🇿": "nz",
    "🇫🇯": "fj",
    "🇵🇬": "pg",
    "🇸🇧": "sb",
    "🇻🇺": "vu",
    "🇳🇨": "nc",
  };
  
  return FLAG_EMOJI_MAP[flagEmoji] || null;
}

const COUNTRY_CODE_MAP: Record<string, string> = {
  "afghanistan": "af",
  "albania": "al",
  "algeria": "dz",
  "argentina": "ar",
  "armenia": "am",
  "australia": "au",
  "austria": "at",
  "azerbaijan": "az",
  "bahrain": "bh",
  "bangladesh": "bd",
  "belarus": "by",
  "belgium": "be",
  "bolivia": "bo",
  "bosnia and herzegovina": "ba",
  "brazil": "br",
  "bulgaria": "bg",
  "cambodia": "kh",
  "canada": "ca",
  "chile": "cl",
  "china": "cn",
  "colombia": "co",
  "costa rica": "cr",
  "croatia": "hr",
  "cuba": "cu",
  "cyprus": "cy",
  "czech republic": "cz",
  "denmark": "dk",
  "dominican republic": "do",
  "ecuador": "ec",
  "egypt": "eg",
  "estonia": "ee",
  "ethiopia": "et",
  "finland": "fi",
  "france": "fr",
  "georgia": "ge",
  "germany": "de",
  "ghana": "gh",
  "greece": "gr",
  "guatemala": "gt",
  "honduras": "hn",
  "hungary": "hu",
  "iceland": "is",
  "india": "in",
  "indonesia": "id",
  "iran": "ir",
  "iraq": "iq",
  "ireland": "ie",
  "israel": "il",
  "italy": "it",
  "jamaica": "jm",
  "japan": "jp",
  "jordan": "jo",
  "kazakhstan": "kz",
  "kenya": "ke",
  "kuwait": "kw",
  "kyrgyzstan": "kg",
  "latvia": "lv",
  "lebanon": "lb",
  "libya": "ly",
  "lithuania": "lt",
  "luxembourg": "lu",
  "malaysia": "my",
  "mexico": "mx",
  "moldova": "md",
  "mongolia": "mn",
  "morocco": "ma",
  "nepal": "np",
  "netherlands": "nl",
  "new zealand": "nz",
  "nicaragua": "ni",
  "nigeria": "ng",
  "north korea": "kp",
  "norway": "no",
  "oman": "om",
  "pakistan": "pk",
  "panama": "pa",
  "paraguay": "py",
  "peru": "pe",
  "philippines": "ph",
  "poland": "pl",
  "portugal": "pt",
  "qatar": "qa",
  "romania": "ro",
  "russia": "ru",
  "saudi arabia": "sa",
  "serbia": "rs",
  "singapore": "sg",
  "slovakia": "sk",
  "slovenia": "si",
  "south africa": "za",
  "south korea": "kr",
  "spain": "es",
  "sri lanka": "lk",
  "sweden": "se",
  "switzerland": "ch",
  "syria": "sy",
  "taiwan": "tw",
  "tajikistan": "tj",
  "thailand": "th",
  "tunisia": "tn",
  "turkey": "tr",
  "turkmenistan": "tm",
  "ukraine": "ua",
  "united arab emirates": "ae",
  "united kingdom": "gb",
  "united states": "us",
  "uruguay": "uy",
  "uzbekistan": "uz",
  "venezuela": "ve",
  "vietnam": "vn",
  "yemen": "ye",
  "zimbabwe": "zw",
  "usa": "us",
  "uk": "gb",
  "uae": "ae",
};

const LANGUAGE_FLAG_MAP: Record<string, string> = {
  "en": "gb",
  "es": "es",
  "fr": "fr",
  "de": "de",
  "it": "it",
  "pt": "pt",
  "ru": "ru",
  "ja": "jp",
  "ko": "kr",
  "zh": "cn",
  "ar": "sa",
  "hi": "in",
  "tr": "tr",
  "pl": "pl",
  "nl": "nl",
  "sv": "se",
  "no": "no",
  "da": "dk",
  "fi": "fi",
  "el": "gr",
  "he": "il",
  "th": "th",
  "vi": "vn",
  "id": "id",
  "ms": "my",
  "tl": "ph",
  "uk": "ua",
  "bg": "bg",
  "cs": "cz",
  "sk": "sk",
  "sl": "si",
  "hr": "hr",
  "sr": "rs",
  "ro": "ro",
  "hu": "hu",
  "et": "ee",
  "lv": "lv",
  "lt": "lt",
};

export function getCountryFlagUrl(countryInput: string | { flag?: string; value?: string; label?: string }): string {
  if (typeof countryInput === 'object' && countryInput !== null) {
    if (countryInput.flag) {
      if (countryInput.flag.length > 2) {
        const emojiCode = flagEmojiToCountryCode(countryInput.flag);
        if (emojiCode) {
          return `https://flagcdn.com/w40/${emojiCode}.png`;
        }
      } else {
        return `https://flagcdn.com/w40/${countryInput.flag.toLowerCase()}.png`;
      }
    }
    const countryName = countryInput.value || countryInput.label || '';
    const code = COUNTRY_CODE_MAP[countryName.toLowerCase()];
    return code
      ? `https://flagcdn.com/w40/${code}.png`
      : `https://flagcdn.com/w40/un.png`;
  }

  const code = COUNTRY_CODE_MAP[countryInput.toLowerCase()];
  return code
    ? `https://flagcdn.com/w40/${code}.png`
    : `https://flagcdn.com/w40/un.png`;
}

export function getLanguageFlagUrl(languageInput: string | { flag?: string; value?: string; label?: string }): string {
  if (typeof languageInput === 'object' && languageInput !== null) {
    if (languageInput.flag) {
      if (languageInput.flag.length > 2) {
        const emojiCode = flagEmojiToCountryCode(languageInput.flag);
        if (emojiCode) {
          return `https://flagcdn.com/w40/${emojiCode}.png`;
        }
      } else {
        return `https://flagcdn.com/w40/${languageInput.flag.toLowerCase()}.png`;
      }
    }
    const langCode = languageInput.value || '';
    const countryCode = LANGUAGE_FLAG_MAP[langCode.toLowerCase()];
    return countryCode
      ? `https://flagcdn.com/w40/${countryCode}.png`
      : `https://flagcdn.com/w40/un.png`;
  }

  const countryCode = LANGUAGE_FLAG_MAP[languageInput.toLowerCase()];
  return countryCode
    ? `https://flagcdn.com/w40/${countryCode}.png`
    : `https://flagcdn.com/w40/un.png`;
}